name: b_ball
description: A new Flutter project.
publish_to: 'none'  
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  bloc: ^8.0.3
  cached_network_image: ^3.2.1
  cloud_firestore: ^3.4.1
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  firebase_core: ^1.20.0
  firebase_auth: ^3.5.1
  flutter_bloc: ^8.0.1
  flutter_screenutil: ^5.5.3+2
  flutter_spinkit: ^5.1.0
  get_it: ^7.2.0
  google_fonts: ^3.0.1
  google_sign_in: ^5.4.0
  persistent_bottom_nav_bar: ^4.0.2
  social_login_buttons: ^1.0.6+2
  validators: ^3.0.0


 

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
flutter:

  uses-material-design: true