// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAG3H9zx4oB1XTueaXhMcEF9xMvT0F6Lx0',
    appId: '1:518046285186:web:376fec6950e3289b47e39b',
    messagingSenderId: '518046285186',
    projectId: 'bball-7d457',
    authDomain: 'bball-7d457.firebaseapp.com',
    storageBucket: 'bball-7d457.appspot.com',
    measurementId: 'G-BNK4ECMWYF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRBLesXjEkksIwyZWPje6QTPMDzH0_d34',
    appId: '1:518046285186:android:e1ca3a2bb583a6bb47e39b',
    messagingSenderId: '518046285186',
    projectId: 'bball-7d457',
    storageBucket: 'bball-7d457.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBjHOkt_n9Rr-Y9Hvo3U9-t-NPzn1vs-8',
    appId: '1:518046285186:ios:8aa2403ca82def1f47e39b',
    messagingSenderId: '518046285186',
    projectId: 'bball-7d457',
    storageBucket: 'bball-7d457.appspot.com',
    androidClientId: '518046285186-n46tbhm1udbtc0vut55fqsal7sl20rni.apps.googleusercontent.com',
    iosClientId: '518046285186-82he3dt7aaku3ivv21pqsb9hp87ipp9e.apps.googleusercontent.com',
    iosBundleId: 'com.example.bBall',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBjHOkt_n9Rr-Y9Hvo3U9-t-NPzn1vs-8',
    appId: '1:518046285186:ios:8aa2403ca82def1f47e39b',
    messagingSenderId: '518046285186',
    projectId: 'bball-7d457',
    storageBucket: 'bball-7d457.appspot.com',
    androidClientId: '518046285186-n46tbhm1udbtc0vut55fqsal7sl20rni.apps.googleusercontent.com',
    iosClientId: '518046285186-82he3dt7aaku3ivv21pqsb9hp87ipp9e.apps.googleusercontent.com',
    iosBundleId: 'com.example.bBall',
  );
}
